### ISSUE TITLE
Inconsistent README

### ISSUE THREAD

**Issue by parasg1999** [BITSoC/BITSoC.github.io#2]
In README, there is some inconsistency
```
Runs at localhost port 4000
.
.
at localhost:5000 or make a PR to view at BITSoC
```

The `_config.yml` file mentions port 5000, so that should be mentioned.

**Comment by GOSHROW** [comment]
Thanks @parasg1999 for raising this issue. Fixed in https://github.com/BITSoC/BITSoC.github.io/commit/e466e5122c90a3e43c1c48ec5b664bf220029fe5 
Hope to have you participate in the event.

**Comment by parasg1999** [comment]
@GOSHROW For sure, I hope to get selected!

**Comment by vaibhavrajsingh2001** [comment]
@parasg1999 your idea is definitely intriguing. Let's hope for the best😁
